pool:
  vmImage: 'ubuntu-16.04'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'


  - script: 'pip3 install twine'

  - task: TwineAuthenticate@0
    inputs:
      artifactFeeds: 'distributions'
      externalFeeds: 'pypi_connection'
  - script: 'python3 setup.py sdist'
  - script: 'twine upload -r client-setup-builds --config-file $(PYPIRC_PATH) dist/*'
  - script: 'twine upload --config-file $(PYPIRC_PATH) dist/*'
