pool:
  vmImage: 'ubuntu-16.04'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'


  - script: 'pip3 install twine'

  - task: TwineAuthenticate@0
    inputs:
      artifactFeeds: 'distributions'
      externalFeeds: 'pypi_connection'
  - script: 'python3 setup.py sdist'
  - script: 'twine upload -r distributions --config-file $(PYPIRC_PATH) dist/*'
  - script: 'twine upload -r pypi_connection --config-file $(PYPIRC_PATH) dist/*'
